### ISSUE TITLE
Todo 관련 코드 리팩토링 회의 

### ISSUE THREAD

**Issue by ericagong** [FindBestPractice/TodoList#2]
### 클린 코드
- [x]  삼항 연산자 → AND 연산자 수정

### 코드 스타일 
- [x]  snake_case → 컨벤션에 맞게 수정
- [x]  기타 줄넘김 수정

### 디렉토리 구조 변경
- [x]  파일 구조 변경 
    
    **todo**
    **ㄴ Form => CreateTodo**
    **ㄴ TodoListFrame => TodoContainer**
    **ㄴ todolist**
    **ㄴ List => TodoList
    ㄴ Todo => Todo**
    ㄴ ReadTodo 
    ㄴ UpdateTodo 
    

### 컴포넌트 관련 변경사항
- [x] 난해한 컴포넌트 명칭 변경  : Frame → Container로 명칭 변경
- [x] 반복 사용 컴포넌트 추가:  Footer.jsx + Header.jsx를 묶어 Layout 컴포넌트로 추가

### 디자인 관련 변경 사항
- [ ]  <del>ThemeProvider 만들어서 css 관리(color 등)</del>

### 성능 개선
- [x]  ReadTodo.jsx: slice 부분 (…)  css 구현 통해 성능 개선
    #### 변경 전 코드
    ```jsx
    import styled from 'styled-components'
   
    const ReadTodo = ({ id, todo, isCompleted, toggleUpdate, deleteTodo }) => {
      ...
    
      return (
        <>
          <StStatus>{isCompleted ? '완료' : '진행중'}</StStatus>
          <StTodo>
            {todo?.length <= 28 ? todo : todo?.slice(0, 26).concat('...')}
          </StTodo>
          <StButtons>
            <StButton onClick={toggleUpdate}>수정하기</StButton>
            <StButton onClick={deleteHandler}>삭제하기</StButton>
          </StButtons>
        </>
      )
    }
    
    export default ReadTodo
    
    const StFont = styled.div`
      font-family: 'Noto Sans KR';
      font-style: normal;
      font-weight: 500;
      letter-spacing: -0.5px;
    `
    
    const StTodo = styled(StFont)`
      font-size: 1rem;
      margin-bottom: 15px;
        `
    `
    ```
    #### 변경 후 코드
    ```jsx
     import styled from 'styled-components'
    
    const ReadTodo = ({ id, todo, isCompleted, toggleUpdate, deleteTodo }) => {
      ...
      return (
        <>
          <StStatus>{isCompleted ? '완료' : '진행중'}</StStatus>
          <StTodo>{todo}</StTodo>
          <StButtons>
            <StButton onClick={toggleUpdate}>수정하기</StButton>
            <StButton onClick={deleteHandler}>삭제하기</StButton>
          </StButtons>
        </>
      )
    }
    
    export default ReadTodo
    
    const StFont = styled.div`
      font-family: 'Noto Sans KR';
      font-style: normal;
      font-weight: 500;
      letter-spacing: -0.5px;
    `
    
    const StTodo = styled(StFont)`
      font-size: 1rem;
      margin-bottom: 15px;
    
      width: calc(100% - 10px);
      overflow: hidden;
      text-overflow: ellipsis;
        white-space: nowrap;
      `
    ```

**Comment by ericagong** [comment]
@dldnjswns31 상기 변경사항 모두 반영하여 `todo` 브랜치에 올려두었습니다. ThemeProvider 연결해 주신 이후에 이슈 닫아주세요 😄

**Comment by dldnjswns31** [comment]
넵 알겠습니다.

**Comment by dldnjswns31** [comment]
Refactoring 단계에서 ThemeProvider를 사용하니 복잡성이 더욱 증가하므로 ThemeProvider 적용 사항은 반려하겠습니다.

**Comment by dldnjswns31** [comment]
Issue closing 하겠습니다.
